/** Mapa nombre de entidad federativa (normalizado) → clave SAT de estado. */
export const MEXICAN_STATE_NAME_TO_CODE: Record<string, string> = {
  aguascalientes: "AGU",
  "baja california": "BCN",
  "baja california sur": "BCS",
  campeche: "CAM",
  chiapas: "CHP",
  chihuahua: "CHH",
  "ciudad de mexico": "CMX",
  "cdmx": "CMX",
  "distrito federal": "CMX",
  coahuila: "COA",
  "coahuila de zaragoza": "COA",
  colima: "COL",
  durango: "DUR",
  guanajuato: "GUA",
  guerrero: "GRO",
  hidalgo: "HID",
  jalisco: "JAL",
  mexico: "MEX",
  "estado de mexico": "MEX",
  michoacan: "MIC",
  "michoacan de ocampo": "MIC",
  morelos: "MOR",
  nayarit: "NAY",
  "nuevo leon": "NLE",
  oaxaca: "OAX",
  puebla: "PUE",
  queretaro: "QUE",
  "quintana roo": "ROO",
  "san luis potosi": "SLP",
  sinaloa: "SIN",
  sonora: "SON",
  tabasco: "TAB",
  tamaulipas: "TAM",
  tlaxcala: "TLA",
  veracruz: "VER",
  "veracruz de ignacio de la llave": "VER",
  yucatan: "YUC",
  zacatecas: "ZAC",
};
